
#include <nusys.h>
#include <nualsgi_n.h>

#include "audio_defines.h"

// Generated by the spec file
extern u8 _dm_seqSegmentRomStart[];
extern u8 _dm_seqSegmentRomEnd[];
extern u8 _dm_bankSegmentRomStart[];
extern u8 _dm_bankSegmentRomEnd[];
extern u8 _dm_tableSegmentRomStart[];
extern u8 _dm_tableSegmentRomEnd[];

#define DEFAULT_NUSYSTEM_BGM_PLAYER 0

#define TRACK_0_DISTANT_MEMORY 0

const TrackInformation trackData[] = {
	{
		"Distant Memory",
		"POLARIA POYON",
		479999,
		7.802f,
		60.9f
	}
};


void initializeAudioLogic() {
}

void playBossMusic() {
  stopAllMusic();

  // Using Distant Memory as the boss music for now 
  nuAuSeqPlayerBankSet(_dm_bankSegmentRomStart, _dm_bankSegmentRomEnd - _dm_bankSegmentRomStart, _dm_tableSegmentRomStart);
  nuAuSeqPlayerSeqSet(_dm_seqSegmentRomStart);
  nuAuSeqPlayerSetNo(DEFAULT_NUSYSTEM_BGM_PLAYER, TRACK_0_DISTANT_MEMORY);

  nuAuSeqPlayerPlay(DEFAULT_NUSYSTEM_BGM_PLAYER);
}


void stopAllMusic() {
	nuAuSeqPlayerStop(DEFAULT_NUSYSTEM_BGM_PLAYER);
}